### ISSUE TITLE
EPIC > Kubelt GitHub Action

### ISSUE THREAD

**Issue by alfl** [kubelt/web3-publish#1]
# Why

The GitHub Action is a user experience experiment. The hypothesis is that developers will like managing their data in git or LFS and publishing it using an action with a versionable config, etc.

The vision is that this will allow developers to easily publish data via, eg, an automated build system. The CMS dapp UI will then allow them to see and edit this content (assumes they login with the same secrets and so can generate the same keys via KDF).

# How

We're starting with IPNS names based on deterministic key generation and moving ASAP to our hypercore naming system.

Ship an action, or collection of actions, that:

- [x] Use key derivation to deterministically generate publishing keys.
- [x] Add content to IPFS and get back CID(s).
- [x] Publish those CIDs as names using generated keys (eventually hypercore).
- [x] Regularly re-publish the desired (~most recent?) CIDs so that the names don't expire.

# What

Checkmark is "processed" -- either done, will not do, or converted to an issue and closed.

- [x] Make repo for a production version of the action and land these issues there.
- [x] Might require protobuf support.
- [x] #2
- [x] Make kubelt/repo for the non-skateboard action.
- [x] #5
- [ ] #6
- [x] #7
- [x] Docs: add notes about how the action works to README.md.
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] Creating a secret within a GitHub Action to store generated keys?
- [x] Wallet login? Dapp? GitHub Secret.
- [x] #4
- [x] #13
- [x] #14
- [x] #3

**Comment by maurerbot** [comment]
@alfl I think we can update this to not use KDF for names.
